name: Run the Eldev Linter

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1

    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Run the linter
        run: |
          eldev lint
